import { SheetColumn } from "@/types/sheet-management";

export const defaultBookingColumns: SheetColumn[] = [
  {
    id: "bookingId",
    name: "Booking ID",
    type: "string",
    required: true,
    width: 120,
    order: 1,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "bookingCode",
    name: "Booking Code",
    type: "string",
    required: true,
    width: 120,
    order: 2,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "tourCode",
    name: "Tour Code",
    type: "string",
    required: true,
    width: 120,
    order: 3,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "reservationDate",
    name: "Reservation Date",
    type: "date",
    required: true,
    width: 140,
    order: 4,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "bookingType",
    name: "Booking Type",
    type: "select",
    required: true,
    width: 120,
    options: ["Individual", "Group", "Corporate"],
    order: 5,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "bookingStatus",
    name: "Booking Status",
    type: "select",
    required: true,
    width: 120,
    options: ["Confirmed", "Pending", "Cancelled", "Completed"],
    order: 6,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "daysBetweenBookingAndTour",
    name: "Days Between Booking and Tour Date",
    type: "number",
    required: false,
    width: 200,
    order: 7,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "groupId",
    name: "Group ID / Group ID Generator",
    type: "string",
    required: false,
    width: 180,
    order: 8,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "isMainBooker",
    name: "Is Main Booker?",
    type: "boolean",
    required: false,
    width: 140,
    order: 9,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "delete",
    name: "Delete",
    type: "function",
    required: false,
    width: 80,
    order: 10,
    visible: true,
    editable: false,
    sortable: false,
    filterable: false,
  },
  {
    id: "travellerInitials",
    name: "Traveller Initials",
    type: "string",
    required: true,
    width: 140,
    order: 11,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "firstName",
    name: "First Name",
    type: "string",
    required: true,
    width: 120,
    order: 12,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "lastName",
    name: "Last Name",
    type: "string",
    required: true,
    width: 120,
    order: 13,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "fullName",
    name: "Full Name",
    type: "string",
    required: false,
    width: 150,
    order: 14,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "emailAddress",
    name: "Email Address",
    type: "email",
    required: true,
    width: 200,
    order: 15,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "tourPackageNameUniqueCounter",
    name: "Tour Package Name Unique Counter",
    type: "number",
    required: false,
    width: 220,
    order: 16,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "tourPackageName",
    name: "Tour Package Name",
    type: "string",
    required: true,
    width: 200,
    order: 17,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "formattedDate",
    name: "Formatted Date",
    type: "string",
    required: false,
    width: 120,
    order: 18,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "tourDate",
    name: "Tour Date",
    type: "date",
    required: true,
    width: 120,
    order: 19,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "returnDate",
    name: "Return Date",
    type: "date",
    required: false,
    width: 120,
    order: 20,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "tourDuration",
    name: "Tour Duration",
    type: "number",
    required: false,
    width: 120,
    order: 21,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "useDiscountedTourCost",
    name: "Use Discounted Tour Cost?",
    type: "boolean",
    required: false,
    width: 180,
    order: 22,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "originalTourCost",
    name: "Original Tour Cost",
    type: "currency",
    required: true,
    width: 140,
    order: 23,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "discountedTourCost",
    name: "Discounted Tour Cost",
    type: "currency",
    required: false,
    width: 140,
    order: 24,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "reservationEmail",
    name: "Reservation Email",
    type: "email",
    required: false,
    width: 200,
    order: 25,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "includeBccReservation",
    name: "Include BCC (Reservation)",
    type: "boolean",
    required: false,
    width: 180,
    order: 26,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "generateEmailDraft",
    name: "Generate Email Draft",
    type: "boolean",
    required: false,
    width: 160,
    order: 27,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "emailDraftLink",
    name: "Email Draft Link",
    type: "string",
    required: false,
    width: 160,
    order: 28,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "subjectLineReservation",
    name: "Subject Line (Reservation)",
    type: "string",
    required: false,
    width: 200,
    order: 29,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "sendEmail",
    name: "Send Email?",
    type: "boolean",
    required: false,
    width: 120,
    order: 30,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "sentEmailLink",
    name: "Sent Email Link",
    type: "string",
    required: false,
    width: 160,
    order: 31,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "reservationEmailSentDate",
    name: "Reservation Email Sent Date",
    type: "date",
    required: false,
    width: 200,
    order: 32,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "paymentCondition",
    name: "Payment Condition",
    type: "select",
    required: false,
    width: 140,
    options: ["Full Payment", "Partial Payment", "Installment"],
    order: 33,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "eligible2ndOfMonths",
    name: "Eligible 2nd-of-Months",
    type: "boolean",
    required: false,
    width: 180,
    order: 34,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "availablePaymentTerms",
    name: "Available Payment Terms",
    type: "string",
    required: false,
    width: 180,
    order: 35,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "paymentPlan",
    name: "Payment Plan",
    type: "select",
    required: false,
    width: 140,
    options: ["Monthly", "Quarterly", "Custom"],
    order: 36,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "paymentMethod",
    name: "Payment Method",
    type: "select",
    required: false,
    width: 140,
    options: ["Credit Card", "Bank Transfer", "Cash", "PayPal"],
    order: 37,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "enablePaymentReminder",
    name: "Enable Payment Reminder",
    type: "boolean",
    required: false,
    width: 160,
    order: 38,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "paymentProgress",
    name: "Payment Progress",
    type: "number",
    required: false,
    width: 140,
    order: 39,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "fullPayment",
    name: "Full Payment",
    type: "currency",
    required: false,
    width: 140,
    order: 40,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "fullPaymentDueDate",
    name: "Full Payment Due Date",
    type: "date",
    required: false,
    width: 160,
    order: 41,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "fullPaymentAmount",
    name: "Full Payment Amount",
    type: "currency",
    required: false,
    width: 160,
    order: 42,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "fullPaymentDatePaid",
    name: "Full Payment Date Paid",
    type: "date",
    required: false,
    width: 160,
    order: 43,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "paymentTerm1",
    name: "Payment Term 1 (Due Date, Amount, Date Paid, Reminder, Email Link, Calendar Event ID/Link)",
    type: "string",
    required: false,
    width: 300,
    order: 44,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "paymentTerm2",
    name: "Payment Term 2 (same structure)",
    type: "string",
    required: false,
    width: 300,
    order: 45,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "paymentTerm3",
    name: "Payment Term 3 (same structure)",
    type: "string",
    required: false,
    width: 300,
    order: 46,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "paymentTerm4",
    name: "Payment Term 4 (same structure)",
    type: "string",
    required: false,
    width: 300,
    order: 47,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "reservationFee",
    name: "Reservation Fee",
    type: "currency",
    required: false,
    width: 140,
    order: 48,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "paid",
    name: "Paid",
    type: "currency",
    required: false,
    width: 100,
    order: 49,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "remainingBalance",
    name: "Remaining Balance",
    type: "currency",
    required: false,
    width: 140,
    order: 50,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "manualCredit",
    name: "Manual Credit",
    type: "currency",
    required: false,
    width: 140,
    order: 51,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "creditFrom",
    name: "Credit From",
    type: "string",
    required: false,
    width: 120,
    order: 52,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "reasonForCancellation",
    name: "Reason for Cancellation",
    type: "string",
    required: false,
    width: 200,
    order: 53,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "includeBccCancellation",
    name: "Include BCC (Cancellation)",
    type: "boolean",
    required: false,
    width: 180,
    order: 54,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "generateCancellationEmailDraft",
    name: "Generate Cancellation Email Draft",
    type: "boolean",
    required: false,
    width: 200,
    order: 55,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "cancellationEmailDraftLink",
    name: "Cancellation Email Draft Link",
    type: "string",
    required: false,
    width: 200,
    order: 56,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "subjectLineCancellation",
    name: "Subject Line (Cancellation)",
    type: "string",
    required: false,
    width: 200,
    order: 57,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "sendCancellationEmail",
    name: "Send Cancellation Email?",
    type: "boolean",
    required: false,
    width: 180,
    order: 58,
    visible: true,
    editable: true,
    sortable: true,
    filterable: true,
  },
  {
    id: "sentCancellationEmailLink",
    name: "Sent Cancellation Email Link",
    type: "string",
    required: false,
    width: 200,
    order: 59,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
  {
    id: "cancellationEmailSentDate",
    name: "Cancellation Email Sent Date",
    type: "date",
    required: false,
    width: 200,
    order: 60,
    visible: true,
    editable: false,
    sortable: true,
    filterable: true,
  },
];
