import { SheetData } from "@/types/sheet-management";

export const demoBookingData: SheetData[] = [
  {
    id: "1",
    bookingId: "BK001",
    bookingCode: "BC001",
    tourCode: "TC001",
    reservationDate: "2024-01-15",
    bookingType: "Individual",
    bookingStatus: "Confirmed",
    daysBetweenBookingAndTour: 59,
    groupId: "GRP001",
    isMainBooker: true,
    travellerInitials: "JD",
    firstName: "John",
    lastName: "Doe",
    fullName: "John Doe",
    emailAddress: "john.doe@example.com",
    tourPackageNameUniqueCounter: 1,
    tourPackageName: "Bali Adventure Tour",
    formattedDate: "15 Mar 2024",
    tourDate: "2024-03-15",
    returnDate: "2024-03-22",
    tourDuration: 8,
    useDiscountedTourCost: false,
    originalTourCost: 1200,
    discountedTourCost: 1200,
    reservationEmail: "john.doe@example.com",
    includeBccReservation: true,
    generateEmailDraft: true,
    emailDraftLink: "https://mail.google.com/draft/123",
    subjectLineReservation: "Bali Adventure Tour Confirmation",
    sendEmail: true,
    sentEmailLink: "https://mail.google.com/sent/456",
    reservationEmailSentDate: "2024-01-15",
    paymentCondition: "Full Payment",
    eligible2ndOfMonths: false,
    availablePaymentTerms: "Full payment required",
    paymentPlan: "Full Payment",
    paymentMethod: "Credit Card",
    enablePaymentReminder: false,
    paymentProgress: 100,
    fullPayment: 1200,
    fullPaymentDueDate: "2024-02-15",
    fullPaymentAmount: 1200,
    fullPaymentDatePaid: "2024-01-20",
    paymentTerm1:
      "2024-02-15, 1200, 2024-01-20, false, https://mail.google.com/sent/456, cal_123",
    paymentTerm2: "",
    paymentTerm3: "",
    paymentTerm4: "",
    reservationFee: 100,
    paid: 1200,
    remainingBalance: 0,
    manualCredit: 0,
    creditFrom: "",
    reasonForCancellation: "",
    includeBccCancellation: false,
    generateCancellationEmailDraft: false,
    cancellationEmailDraftLink: "",
    subjectLineCancellation: "",
    sendCancellationEmail: false,
    sentCancellationEmailLink: "",
    cancellationEmailSentDate: "",
  },
  {
    id: "2",
    bookingId: "BK002",
    bookingCode: "BC002",
    tourCode: "TC002",
    reservationDate: "2024-01-20",
    bookingType: "Group",
    bookingStatus: "Pending",
    daysBetweenBookingAndTour: 65,
    groupId: "GRP002",
    isMainBooker: true,
    travellerInitials: "SW",
    firstName: "Sarah",
    lastName: "Wilson",
    fullName: "Sarah Wilson",
    emailAddress: "sarah.wilson@example.com",
    tourPackageNameUniqueCounter: 2,
    tourPackageName: "Thailand Cultural Experience",
    formattedDate: "20 Mar 2024",
    tourDate: "2024-03-20",
    returnDate: "2024-03-28",
    tourDuration: 9,
    useDiscountedTourCost: true,
    originalTourCost: 1800,
    discountedTourCost: 1620,
    reservationEmail: "sarah.wilson@example.com",
    includeBccReservation: false,
    generateEmailDraft: true,
    emailDraftLink: "https://mail.google.com/draft/789",
    subjectLineReservation: "Thailand Cultural Experience - Group Booking",
    sendEmail: false,
    sentEmailLink: "",
    reservationEmailSentDate: "",
    paymentCondition: "Partial Payment",
    eligible2ndOfMonths: true,
    availablePaymentTerms: "50% deposit, balance 30 days before",
    paymentPlan: "Monthly",
    paymentMethod: "Bank Transfer",
    enablePaymentReminder: true,
    paymentProgress: 60,
    fullPayment: 1620,
    fullPaymentDueDate: "2024-02-20",
    fullPaymentAmount: 1620,
    fullPaymentDatePaid: "",
    paymentTerm1:
      "2024-02-20, 810, 2024-01-25, true, https://mail.google.com/sent/789, cal_456",
    paymentTerm2: "2024-03-20, 810, , true, , cal_789",
    paymentTerm3: "",
    paymentTerm4: "",
    reservationFee: 150,
    paid: 810,
    remainingBalance: 810,
    manualCredit: 0,
    creditFrom: "",
    reasonForCancellation: "",
    includeBccCancellation: false,
    generateCancellationEmailDraft: false,
    cancellationEmailDraftLink: "",
    subjectLineCancellation: "",
    sendCancellationEmail: false,
    sentCancellationEmailLink: "",
    cancellationEmailSentDate: "",
  },
  {
    id: "3",
    bookingId: "BK003",
    bookingCode: "BC003",
    tourCode: "TC003",
    reservationDate: "2024-01-25",
    bookingType: "Corporate",
    bookingStatus: "Confirmed",
    daysBetweenBookingAndTour: 70,
    groupId: "GRP003",
    isMainBooker: true,
    travellerInitials: "MJ",
    firstName: "Mike",
    lastName: "Johnson",
    fullName: "Mike Johnson",
    emailAddress: "mike.johnson@company.com",
    tourPackageNameUniqueCounter: 3,
    tourPackageName: "Vietnam Discovery",
    formattedDate: "25 Mar 2024",
    tourDate: "2024-03-25",
    returnDate: "2024-04-02",
    tourDuration: 9,
    useDiscountedTourCost: false,
    originalTourCost: 2100,
    discountedTourCost: 2100,
    reservationEmail: "mike.johnson@company.com",
    includeBccReservation: true,
    generateEmailDraft: true,
    emailDraftLink: "https://mail.google.com/draft/101",
    subjectLineReservation: "Vietnam Discovery - Corporate Booking",
    sendEmail: true,
    sentEmailLink: "https://mail.google.com/sent/202",
    reservationEmailSentDate: "2024-01-25",
    paymentCondition: "Full Payment",
    eligible2ndOfMonths: false,
    availablePaymentTerms: "Full payment required",
    paymentPlan: "Full Payment",
    paymentMethod: "Credit Card",
    enablePaymentReminder: false,
    paymentProgress: 100,
    fullPayment: 2100,
    fullPaymentDueDate: "2024-02-25",
    fullPaymentAmount: 2100,
    fullPaymentDatePaid: "2024-01-30",
    paymentTerm1:
      "2024-02-25, 2100, 2024-01-30, false, https://mail.google.com/sent/202, cal_101",
    paymentTerm2: "",
    paymentTerm3: "",
    paymentTerm4: "",
    reservationFee: 200,
    paid: 2100,
    remainingBalance: 0,
    manualCredit: 0,
    creditFrom: "",
    reasonForCancellation: "",
    includeBccCancellation: false,
    generateCancellationEmailDraft: false,
    cancellationEmailDraftLink: "",
    subjectLineCancellation: "",
    sendCancellationEmail: false,
    sentCancellationEmailLink: "",
    cancellationEmailSentDate: "",
  },
  {
    id: "4",
    bookingId: "BK004",
    bookingCode: "BC004",
    tourCode: "TC004",
    reservationDate: "2024-01-30",
    bookingType: "Individual",
    bookingStatus: "Cancelled",
    daysBetweenBookingAndTour: 45,
    groupId: "",
    isMainBooker: true,
    travellerInitials: "AL",
    firstName: "Alice",
    lastName: "Lee",
    fullName: "Alice Lee",
    emailAddress: "alice.lee@example.com",
    tourPackageNameUniqueCounter: 4,
    tourPackageName: "Philippines Island Hopping",
    formattedDate: "15 Mar 2024",
    tourDate: "2024-03-15",
    returnDate: "2024-03-22",
    tourDuration: 8,
    useDiscountedTourCost: false,
    originalTourCost: 1500,
    discountedTourCost: 1500,
    reservationEmail: "alice.lee@example.com",
    includeBccReservation: false,
    generateEmailDraft: false,
    emailDraftLink: "",
    subjectLineReservation: "",
    sendEmail: false,
    sentEmailLink: "",
    reservationEmailSentDate: "",
    paymentCondition: "Full Payment",
    eligible2ndOfMonths: false,
    availablePaymentTerms: "Full payment required",
    paymentPlan: "Full Payment",
    paymentMethod: "Credit Card",
    enablePaymentReminder: false,
    paymentProgress: 0,
    fullPayment: 1500,
    fullPaymentDueDate: "2024-02-15",
    fullPaymentAmount: 1500,
    fullPaymentDatePaid: "",
    paymentTerm1: "2024-02-15, 1500, , false, , ",
    paymentTerm2: "",
    paymentTerm3: "",
    paymentTerm4: "",
    reservationFee: 150,
    paid: 0,
    remainingBalance: 1500,
    manualCredit: 0,
    creditFrom: "",
    reasonForCancellation: "Schedule conflict - client requested cancellation",
    includeBccCancellation: true,
    generateCancellationEmailDraft: true,
    cancellationEmailDraftLink: "https://mail.google.com/draft/303",
    subjectLineCancellation: "Philippines Island Hopping - Cancellation",
    sendCancellationEmail: true,
    sentCancellationEmailLink: "https://mail.google.com/sent/404",
    cancellationEmailSentDate: "2024-02-01",
  },
];
